title: Calculator Documentation
description: An application using cool concepts such as Documentation-As-Code (Asciidoctor), Additions and Subtractions
author: Alain Helaili
email: helaili@github.com
source: docs
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
